### ISSUE TITLE
didCatch?

### ISSUE THREAD

**Issue by swyxio** [ryanflorence/react-component-component#2]
seems like its easy enough to include. was leaving it out unintentional? if not am happy to pr

**Comment by maciekmaciej** [comment]
I have the same question about `willUnmount`

**Comment by ryanflorence** [comment]
`willUnmount` died in a terrible copy-from-project-to-this-repo accident. Just put it back in release v1.0.2.

I'm not sure about `didCatch` yet. Probably going to recommend `<ErrorBoundary/>` over putting `didCatch` in here, but I have some open questions about it.
