### ISSUE TITLE
Flow

### ISSUE THREAD

**Issue by skrivle** [ryanflorence/react-component-component#7]
Would you be ok with adding Flow types? I can create a PR if that's ok ...

**Comment by skrivle** [comment]
After looking further into this, it looks like it’s not going to be as straightforward as I originally thought. I’ve noticed that there’s circular dependency in the Props type. When describing the Props you want to define shouldUpdate, didMount, etc... but they receive Props as an in input through getArgs(). Regardless of this flow type issue, I was wondering if this Component was meant to also receive other Props apart from the predefined ones as well.

**Comment by ryanflorence** [comment]
Yeah, it can receive any kind of props, that's the only way you'd be able to do a comparison of prev/next props in some of the hooks.

**Comment by tsiq-swyx** [comment]
tried to use this in typescript today and ran into this. i might try to write a .d.ts for this.

**Comment by eddiemoore** [comment]
@tsiq-swyx There is a PR open for the Typescript definitions #11 

Could check that out and see if it's all working

**Comment by swyxio** [comment]
@eddiemoore  made my own https://github.com/sw-yx/react-classless

**Comment by dyst5422** [comment]
Heres a .d.ts that I use with typescript that has all the great stuff you would want

```ts
declare module 'react-component-component' {
  interface Props<S> {
    // tslint:disable-next-line:no-any
    [key: string]: any,
    initialState?: S;
    didMount?: (
      opts: {
        state: S;
        setState: (state: Partial<S>) => void;
        props: Props<S>;
        forceUpdate: (callBack?: () => void) => void;
      },
    ) => void;
    shouldUpdate?: (
      opts: { state: S; setState: (state: Partial<S>) => void; nextProps: Props<S>; nextState: S },
    ) => boolean;
    didUpdate?: (
      opts: {
        state: S;
        setState: (state: Partial<S>) => void;
        props: Props<S>;
        forceUpdate: (callBack?: () => void) => void;
        prevProps: Props<S>;
        prevState: S;
      },
    ) => void;
    willUnmount?: (opts: { state: S; props: Props<S> }) => void;
    children: (
      opts: {
        state: S;
        setState: ((state: Partial<S> | ((state: S) => S)) => void);
        props: Props<S>;
        forceUpdate: (callBack?: () => void) => void;
      },
    ) => React.ReactNode;
  }
  export default class Component<State> extends React.Component<Props<State>, State> {}
}

```
