### ISSUE TITLE
Copypaste issue with invariant Error message

### ISSUE THREAD

**Issue by JustFly1984** [ryanflorence/react-component-component#9]
Hello, I just found out about your package thanx to Kent C Dodds email list, and went through the source code.

I found this minor issue, which could be confusing for newcomers.

Have a nice day!

```
componentWillReceiveProps(nextProps, nextState) {
    invariant(
      !this.props.willReceiveProps,
      "<Component> Please use `didUpdate` instead of `willReceiveProps`."
    );
  }

  componentWillUpdate(nextProps, nextState) {
    invariant(
      !this.props.willUpdate,
      "<Component> Please use `didUpdate` instead of `willReceiveProps`."
    );
  }
```

```"<Component> Please use `didUpdate` instead of `willReceiveProps`."```
should be replaced  with```"<Component> Please use `didUpdate` instead of `willUpdate`."```

**Comment by ryanflorence** [comment]
Removed those warning anyway, but thanks!
